### ISSUE TITLE
PvC not working breakdown

### ISSUE THREAD

**Issue by IronhideIvan** [kebin20/tic-tac-toe-react#1]
Yo!

Wasn't sure how best to go about creating a documented discussion on your project so I went ahead and am creating an issue.

Let's focus on `PvCGame.jsx`, where you're struggling. There are a couple things that to be addressed so lets start breaking things down. Specifically we want to look at these two functions

``` js
  function computerPlay(icon) {
    const availableSpaces = board.filter(
      (space) => space !== "X" && space !== "O"
    );
    const move =
      availableSpaces[Math.floor(Math.random() * availableSpaces.length)];

    const boardCopy = [...board];
    boardCopy[move] = icon;
    return icon;
  }

  function handleClick(i) {
    const boardCopy = [...board];
    // If user click a filled in square or if game is won, return
    if (winner || boardCopy[i]) return;
    // Insert an O or an X into the square depending on the player
    let value = "O";
    if (xIsNext) {
      if (props.playerOne === "X" || props.playerCpu === "X") {
        if (props.playerOne === "X") {
          value = "X";
        } else if (props.playerCpu === "X") {
          value = computerPlay("X");
        }
        if (props.playerOne === "O" || props.playerCpu === "O") {
          if (props.playerOne === "O") {
            value = "O";
          } else if (props.playerCpu === "O") {
            value = computerPlay("O");
          }
        }
      }
    }
    boardCopy[i] = value;
    setBoard(boardCopy);
    setXisNext(!xIsNext);
  }
```

### Computer Move Choice

First, lets breakdown `computerPlay`

``` js
    const availableSpaces = board.filter(
      (space) => space !== "X" && space !== "O"
    );
    const move =
      availableSpaces[Math.floor(Math.random() * availableSpaces.length)];
```

Firstly, `move` will always be null and not an integer because that's the only values within `availableSpaces`.

Secondly, the issue you're going to run into here is that the random number that's being generated doesn't accurately reflect an empty space in the board. This is because all `availableSpaces` will be is a smaller array from `board`, so when a random number is generated then an index at that number still isn't guaranteed to be available in `board`. For example, let's say this is `board`:

[null, null, X, null, null]

index 2 is the only index that's not null. So now after we generate `availableSpaces` we get an array that looks like this:

[null, null, null, null]

if we generate a random integer with a max of `availableSpaces.length` then there is still the possibility of drawing an index of '2'.

One solution would be to create an array `availableIndeces` where its contents are the available indexes within `board` which don't have a value. For example, using our example board from earlier `availableIndeces` could look like:

[0, 1, 3, 4].

### computerPlay function

Given the move choice logic was finished, I would rewrite the function a little bit.

``` js
function computerPlay(localBoard, icon) {
    // Randomizer logic

    localBoard[move] = icon;
  }
```

I think it's cleaner if you pass in the board that the computer should care about directly to the function, since you're working with a copy in `handleClick`. That way the function knows exactly which board it needs to care about and alter instead of making its own copy that it needs to pass back.

### handleClick

I feel like you are overthinking how the player and CPU interact. All that needs to happen is:

1. We fill in whatever spot the player clicked if it's available
2. then, we let the CPU fill in a random spot that's still available
3. update the board
4. wait for the next click

From the player's perspective, it will always be there turn because the CPU responds instantly so there is no need to check who's turn it is. The procedure can be rewritten to:

``` js
function handleClick(i) {
    const boardCopy = [...board];

    // If user click a filled in square or if game is won, return
    if (winner || boardCopy[i]) return;

    const cpuValue = props.playerOne === "X" ? "O" : "X";
    boardCopy[i] = props.playerOne;
    computerPlay(boardCopy, cpuValue); // <-- Since we've altered the board with the player's choice, it's important to be able to 
                                                                  // pass it down to the CPU move logic
    setBoard(boardCopy);
  }
```

### Code quality thoughts

This is more of a personal preference, but I'm not a fan of having lots of the same strings beings used like in here:

``` js
if (props.playerOne === "X" || props.playerCpu === "X") {
        if (props.playerOne === "X") {
          value = "X";
        } else if (props.playerCpu === "X") {
          value = computerPlay("X");
        } 
```

It's only a single letter in a fairly small app, but in larger strings it makes it really easy to fat-finger a letter by accident and it won't be caught by compilation errors since you're comparing a string. additionally, if the string ever needs to change it mean that it needs to be changed in every single spot it's being used. can get very old quickly 😄 . 

I prefer to put strings being used multiple times into some sort of constant variable, for example something like `optionX` or `optionO` for the tic-tac-toe app (although it won't be as necessary after the changes to `handleClick`, just something to keep in mind for future changes).

**Comment by kebin20** [comment]
Hey Peter! 

Thank you so much for your feedback and help, I've fixed some of the problem points that you pointed out: 

### **Computer Move Choice**

For this part, you made a very good point in that using filter() makes the array smaller which we don't want. So after ruminating and thinking, I decided to create an empty array called availableIndices, and used a forEach() method to target the empty spaces and its index and push it into the availableIndices array. This then, will allow the move variable to randomise that index. 

```
function computerPlay(localBoard, icon) {
    const availableIndices = [];
    localBoard.forEach((space, index) => {
      if (space !== "X" && space !== "O") {
        return availableIndices.push(index);
      }
    });
```
### **handleClick**
 
For the handleclick function, I would have used your simpler solution to determine the CPU or Player turn, but have decided to use conditional statements since I need other parts of my components to display who the winner is (using playerCpu state)

```
 function handleClick(i) {
    const boardCopy = [...board];
    // If user click a filled in square or if game is won, return
    if (winner || boardCopy[i]) return;
    // Insert an O or an X into the square depending on the player

    let value = "O";
    let cpuValue = "O";

      if (props.playerOne === "X") {
        value = "X";
      } else if (props.playerCpu === "X") {
        cpuValue = "X";
      }

        if (props.playerOne === "O") {
          value = "O";
        } else if (props.playerCpu === "O") {
          cpuValue = "O";
        }

    boardCopy[i] = value;

    computerPlay(boardCopy, cpuValue);
    setBoard(boardCopy);
  }
```

And I will keep the code quality thoughts in mind for my future projects.
